#!/bin/sh
#
# Usage: gputest.sh
# Change job name and email address as needed 
#        
# -- our name ---
#$ -N A2
#$ -S /bin/sh
# Make sure that the .e and .o file arrive in the
#working directory
#$ -cwd
#Merge the standard out and standard error to one file
#$ -j y
# Request a gpu

#$ -q datasci

/bin/echo Running on host: `hostname`.
/bin/echo In directory: `pwd`
/bin/echo Starting on: `date`
 
# Load openmp module
. /opt/modules/init/bash
module load intel/compiler/2017.2.174

#module load gsl-gnu4
#export LD_LIBRARY_PATH=/opt/gsl/1.15/gnu4/lib:$LD_LIBRARY_PATH

#Full path to executable
#Replace usman's home directory path with yours in the command below

/usr/bin/time -f %e -o DP_time_omp ./dp_openmp 3 4 iMatrix.txt iVector.txt 10 > output_omp

